name: Get stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup tools
        run: |
          sudo apt update
          sudo apt install -y fish cargo jq git
          cargo install tokei

      - name: Run stats and generate SVG
        env:
          TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        run: |
          set -ex
          ./stats_total.fish
          python viz_total.py
          ./stats_public.fish
          python viz_public.py
          python stats_recent.py
          python viz_recent.py
          python viz_copilot.py

      - name: Commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Update stats" && git push -f || true
